/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.librecommerce.view;

import br.com.librecommerce.modelo.Cliente;
import br.com.librecommerce.modelo.FormaPagamento;
import br.com.librecommerce.modelo.abstractTableModel.ItemVendaTableModel;
import java.awt.event.KeyEvent;

/**
 *
 * @author Clovis
 */
public class ConfirmarVendaView extends javax.swing.JDialog {

    private ItemVendaTableModel itemVendaTableModel = new ItemVendaTableModel();
    private FormaPagamento formaPagamento;
    private Cliente cliente;
    private boolean clienteSelecionado;
    private boolean confirmar;

    /**
     * Creates new form ConfirmarVendaView
     */
    public ConfirmarVendaView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtValorPago.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSelecionarCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbFormaPagamento = new javax.swing.JComboBox(formaPagamento.values());
        jLabel3 = new javax.swing.JLabel();
        txtAcrescimo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTroco = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        txtValorPago = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LibreCommerce - Confirmar Venda");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cliente:");

        btnSelecionarCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSelecionarCliente.setText("Selecionar Cliente...");
        btnSelecionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarClienteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Forma de Pagamento:");

        cbFormaPagamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Acréscimo:");

        txtAcrescimo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAcrescimo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAcrescimoFocusLost(evt);
            }
        });
        txtAcrescimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAcrescimoKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Desconto:");

        txtDesconto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescontoFocusLost(evt);
            }
        });
        txtDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescontoKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Valor Pago:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Total R$:");

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotal.setText("0.00");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Troco R$:");

        lblTroco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTroco.setText("0.00");

        btnConfirmar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        txtValorPago.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorPagoFocusLost(evt);
            }
        });
        txtValorPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorPagoKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(btnSelecionarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cbFormaPagamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDesconto)
                            .addComponent(txtAcrescimo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValorPago)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotal)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTroco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnSelecionarCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAcrescimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblTroco)
                    .addComponent(btnConfirmar)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAcrescimoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAcrescimoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            calculaTotalAcrescimo();
        }
    }//GEN-LAST:event_txtAcrescimoKeyPressed

    private void txtDescontoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescontoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            calculaTotalDesconto();
        }
    }//GEN-LAST:event_txtDescontoKeyPressed

    private void txtValorPagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorPagoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            calculaTotalValorPago();
        }
    }//GEN-LAST:event_txtValorPagoKeyPressed

    private void btnSelecionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarClienteActionPerformed
        PesquisaClienteView pesquisaClienteView = new PesquisaClienteView(null, true);
        pesquisaClienteView.setLocationRelativeTo(this);
        pesquisaClienteView.setVisible(true);
        if (pesquisaClienteView.isClienteSelecionado()) {
            this.cliente = pesquisaClienteView.getCliente();
            this.btnSelecionarCliente.setText(cliente.getNome());
            this.clienteSelecionado = true;
        }
    }//GEN-LAST:event_btnSelecionarClienteActionPerformed

    private void txtAcrescimoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAcrescimoFocusLost
        calculaTotalAcrescimo();
    }//GEN-LAST:event_txtAcrescimoFocusLost

    private void txtDescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescontoFocusLost
        calculaTotalDesconto();
    }//GEN-LAST:event_txtDescontoFocusLost

    private void txtValorPagoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorPagoFocusLost
        calculaTotalValorPago();
    }//GEN-LAST:event_txtValorPagoFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        this.confirmar = true;
        this.dispose();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void calculaTotalAcrescimo() {
        if (!txtAcrescimo.getText().trim().equals("")) {
            Double valorAcrescimo = Double.parseDouble(txtAcrescimo.getText().replace(",", "."));
            Double total = Double.parseDouble(lblTotal.getText());
            lblTotal.setText(String.valueOf(valorAcrescimo + total));
            txtAcrescimo.setEditable(false);
            txtDesconto.requestFocus();
        }
    }

    private void calculaTotalDesconto() {
        if (!txtDesconto.getText().trim().equals("")) {
            Double valorDesconto = Double.parseDouble(txtDesconto.getText().replace(",", "."));
            Double total = Double.parseDouble(lblTotal.getText());
            lblTotal.setText(String.valueOf(total - valorDesconto));
            txtDesconto.setEditable(false);
            txtValorPago.requestFocus();
        }
    }

    private void calculaTotalValorPago() {
        if (!txtValorPago.getText().trim().equals("")) {
            Double valorPago = Double.parseDouble(txtValorPago.getText().replace(",", "."));
            Double total = Double.parseDouble(lblTotal.getText());
            lblTroco.setText(String.valueOf(valorPago - total));
            btnConfirmar.requestFocus();
        }
    }

    public void setTotal(Double total) {
        this.lblTotal.setText(String.valueOf(total));
    }

    public FormaPagamento getFormaPagamento() {
        return (FormaPagamento) cbFormaPagamento.getSelectedItem();
    }

    public Double getAcrescimo() {
        if (txtAcrescimo.getText().trim().equals("")) {
            return 0.0;
        } else {
            return Double.parseDouble(txtAcrescimo.getText().replace(",", "."));
        }
    }

    public Double getDesconto() {
        if (txtDesconto.getText().trim().equals("")) {
            return 0.0;
        } else {
            return Double.parseDouble(txtDesconto.getText().replace(",", "."));
        }
    }

    public Double getValorPago() {
        if (txtValorPago.getText().trim().equals("")) {
            return 0.0;
        } else {
            return Double.parseDouble(txtValorPago.getText().replace(",", "."));
        }
    }

    public Double getTotal() {
        return Double.parseDouble(lblTotal.getText());
    }

    public Double getTroco() {
        return Double.parseDouble(lblTroco.getText());
    }
    
    public boolean isClienteSelecionado() {
        return clienteSelecionado;
    }
    
    public boolean isConfirmar() {
        return confirmar;
    }
    
    public Cliente getCliente() {
        return cliente;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnSelecionarCliente;
    private javax.swing.JComboBox cbFormaPagamento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTroco;
    private javax.swing.JTextField txtAcrescimo;
    private javax.swing.JTextField txtDesconto;
    private javax.swing.JTextField txtValorPago;
    // End of variables declaration//GEN-END:variables
}
