/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.librecommerce.view;

import br.com.librecommerce.controller.ContaPagarController;
import br.com.librecommerce.modelo.ContaPagar;
import br.com.librecommerce.modelo.StatusConta;
import br.com.librecommerce.modelo.abstractTableModel.ContaPagarTableModel;
import br.com.librecommerce.util.Messages;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Clovis
 */
public class ContaPagarView extends javax.swing.JFrame {
    
    private ContaPagarTableModel contaPagarTableModel = new ContaPagarTableModel();
    private DateFormat df = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form ContaPagarView
     */
    public ContaPagarView() {
        initComponents();
        carregarTodasContas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDataVencimento = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContaPagar = new javax.swing.JTable();
        btnPagar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnPagarTodas = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Descrição:");

        jLabel2.setText("Data de Vencimento:");

        try {
            txtDataVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("Valor:");

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/OK.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        tblContaPagar.setModel(contaPagarTableModel);
        tblContaPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblContaPagarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblContaPagar);

        btnPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/dollar.png"))); // NOI18N
        btnPagar.setText("Pagar");
        btnPagar.setEnabled(false);
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnPagarTodas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Euro.png"))); // NOI18N
        btnPagarTodas.setText("Pagar Todas");
        btnPagarTodas.setEnabled(false);
        btnPagarTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarTodasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtValor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtDescricao))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSalvar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnPagar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPagarTodas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisar)
                    .addComponent(btnSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPagar)
                    .addComponent(btnCancelar)
                    .addComponent(btnPagarTodas))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carregarTodasContas() {
        this.contaPagarTableModel.AddAll(new ContaPagarController().consultarTodas());
    }
    
    private void tblContaPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContaPagarMouseClicked
        btnPagar.setEnabled(true);
        btnPagarTodas.setEnabled(true);
    }//GEN-LAST:event_tblContaPagarMouseClicked

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        if (txtDescricao.getText().trim().equals("")) {
            Messages.alertMessage(this, "Informe a descrição da conta!");
        } else {
            List<ContaPagar> contasPagar = 
                    new ContaPagarController().consultarPorDescricao(txtDescricao.getText());
            if (contasPagar == null || contasPagar.isEmpty()) {
                Messages.alertMessage(this, "Nenhuma conta com esta descrição encontrada!");
            } else {
                this.contaPagarTableModel.AddAll(contasPagar);
            }
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (txtDescricao.getText().trim().equals("") &&
                txtDataVencimento.getText().trim().equals("") &&
                txtValor.getText().trim().equals("")) {
            Messages.alertMessage(this, "Todos os campos são obrigatórios!");
        } else {
            ContaPagar contaPagar = new ContaPagar();
            contaPagar.setDescricao(txtDescricao.getText());
            contaPagar.setValor(Double.parseDouble(txtValor.getText().replace(",", ".")));
            contaPagar.setStatusConta(StatusConta.ABERTA);
            try {
                contaPagar.setDataVencimento(df.parse(txtDataVencimento.getText()));
            } catch (ParseException ex) {
                System.out.println("Erro..." + ex.getMessage());
            }
            if (new ContaPagarController().salvar(contaPagar)) {
                clearFields();
                carregarTodasContas();
                Messages.infoMessage(this, "Conta salva com sucesso!");
            } else {
                Messages.errorMessage(this, "Não foi possível realizar esta operação!");
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        ContaPagar contaSelecionada = 
                this.contaPagarTableModel.getContaPagar(tblContaPagar.getSelectedRow());
        if (new ContaPagarController().pagarConta(contaSelecionada)) {
            carregarTodasContas();
            Messages.infoMessage(this, "Conta paga com sucesso!");
        } else {
            Messages.errorMessage(this, "Não foi possível realizar esta operação!");
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnPagarTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarTodasActionPerformed
        if (new ContaPagarController().pagarTodas(this.contaPagarTableModel.getAll())) {
            carregarTodasContas();
            Messages.infoMessage(this, "Todas as contas foram pagas!");
        } else {
            Messages.errorMessage(this, "Não foi possível realizar esta operação!");
        }
    }//GEN-LAST:event_btnPagarTodasActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void clearFields() {
        this.txtDescricao.setText("");
        this.txtDataVencimento.setText("");
        this.txtValor.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnPagarTodas;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblContaPagar;
    private javax.swing.JFormattedTextField txtDataVencimento;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
