/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.librecommerce.view;

import br.com.librecommerce.controller.ContaReceberController;
import br.com.librecommerce.modelo.ContaReceber;
import br.com.librecommerce.modelo.abstractTableModel.ContaReceberTableModel;
import br.com.librecommerce.util.Messages;
import java.util.List;

/**
 *
 * @author Clovis
 */
public class ContaReceberView extends javax.swing.JFrame {
    
    private ContaReceberTableModel contaReceberTableModel = new ContaReceberTableModel();

    /**
     * Creates new form ContaReceberView
     */
    public ContaReceberView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContaReceber = new javax.swing.JTable();
        btnReceberTodas = new javax.swing.JButton();
        btnReceber = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Cliente:");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        tblContaReceber.setModel(contaReceberTableModel);
        tblContaReceber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblContaReceberMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblContaReceber);

        btnReceberTodas.setText("ReceberTodas");
        btnReceberTodas.setEnabled(false);
        btnReceberTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceberTodasActionPerformed(evt);
            }
        });

        btnReceber.setText("Receber");
        btnReceber.setEnabled(false);
        btnReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnReceber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReceberTodas)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReceberTodas)
                    .addComponent(btnReceber))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carregarTodasContas() {
        this.contaReceberTableModel.addAll(new ContaReceberController().consultarTodas());
    }
    
    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        if (txtNome.getText().trim().equals("")) {
            Messages.alertMessage(this, "Informe o nome do Cliente!");
        } else {
            List<ContaReceber> contasReceber = 
                    new ContaReceberController().consultarPorCliente(txtNome.getText());
            if (contasReceber == null || contasReceber.isEmpty()) {
                Messages.alertMessage(this, "Nenhum Cliente com este nome encontrado!");
            } else {
                this.contaReceberTableModel.addAll(contasReceber);
            }
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceberActionPerformed
        ContaReceber contaSelecionada = 
                this.contaReceberTableModel.getContaReceber(tblContaReceber.getSelectedRow());
        if (new ContaReceberController().receber(contaSelecionada)) {
            carregarTodasContas();
            Messages.infoMessage(this, "Conta recebida!");
        } else {
            Messages.errorMessage(this, "Não foi possível realizar esta operação!");
        }
    }//GEN-LAST:event_btnReceberActionPerformed

    private void btnReceberTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceberTodasActionPerformed
        if (new ContaReceberController().receberTodas(this.contaReceberTableModel.getAll())) {
            carregarTodasContas();
            Messages.infoMessage(this, "Todas as contas foram recebidas!");
        } else {
            Messages.errorMessage(this, "Não foi possível realizar esta operação!");
        }
    }//GEN-LAST:event_btnReceberTodasActionPerformed

    private void tblContaReceberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContaReceberMouseClicked
        btnReceber.setEnabled(true);
        btnReceberTodas.setEnabled(true);
    }//GEN-LAST:event_tblContaReceberMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnReceber;
    private javax.swing.JButton btnReceberTodas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblContaReceber;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
