/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.librecommerce.view;

import br.com.librecommerce.controller.CaixaController;
import br.com.librecommerce.modelo.Caixa;
import br.com.librecommerce.modelo.Funcionario;
import br.com.librecommerce.modelo.StatusCaixa;
import br.com.librecommerce.util.Messages;
import br.com.librecommerce.util.Session;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Clovis
 */
public class PrincipalView extends javax.swing.JFrame {

    private ClienteView clienteView;
    private FornecedorView fornecedorView;
    private FuncionarioView funcionarioView;
    private NovaVendaView novaVendaView;
    private ProdutoView produtoView;
    
    private ContaReceberView contaReceberView;
    private ContaPagarView contaPagarView;

    private Caixa caixa;
    private Funcionario funcionario;

    /**
     * Creates new form PrincipalView
     *
     * @param funcionario
     */
    public PrincipalView() {
        this.caixa = getCaixaAberto();
        if (this.caixa == null) {
            caixa = new Caixa();
        }
        this.funcionario = (Funcionario) Session.getInstance().getSessionMap().get("funcionario");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnAbrirCaixa = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnFecharCaixa = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnRealizarSangria = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnNovaVenda = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        lblStatusCaixa = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuClientes = new javax.swing.JMenuItem();
        menuFornecedores = new javax.swing.JMenuItem();
        menuFuncionarios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuProdutos = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuContasReceber = new javax.swing.JMenuItem();
        menuContasPagar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LibreCommerce - PDV");

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnAbrirCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/abrir-caixa.png"))); // NOI18N
        btnAbrirCaixa.setText("Abrir Caixa");
        btnAbrirCaixa.setFocusable(false);
        btnAbrirCaixa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbrirCaixa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbrirCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirCaixaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAbrirCaixa);
        jToolBar1.add(jSeparator3);

        btnFecharCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fechar-caixa.png"))); // NOI18N
        btnFecharCaixa.setText("Fechar Caixa");
        btnFecharCaixa.setFocusable(false);
        btnFecharCaixa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFecharCaixa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFecharCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharCaixaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFecharCaixa);
        jToolBar1.add(jSeparator4);

        btnRealizarSangria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/realizar-sangria.png"))); // NOI18N
        btnRealizarSangria.setText("Realizar Sangria");
        btnRealizarSangria.setFocusable(false);
        btnRealizarSangria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRealizarSangria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRealizarSangria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarSangriaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRealizarSangria);
        jToolBar1.add(jSeparator5);

        btnNovaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nova-venda.png"))); // NOI18N
        btnNovaVenda.setText("Nova Venda");
        btnNovaVenda.setFocusable(false);
        btnNovaVenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovaVenda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaVendaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNovaVenda);

        jToolBar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        jLabel1.setText("Caixa:  ");
        jToolBar2.add(jLabel1);

        lblStatusCaixa.setText(this.caixa.getStatusCaixa() == null ? "FECHADO" : "ABERTO");
        jToolBar2.add(lblStatusCaixa);
        jToolBar2.add(jSeparator6);

        jLabel2.setText("Funcionário Logado:  ");
        jToolBar2.add(jLabel2);

        jLabel3.setText(this.funcionario.isAdmin() ? this.funcionario.getNome()+" :: Admin" : this.funcionario.getNome()+" :: Operador");
        jToolBar2.add(jLabel3);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastro.png"))); // NOI18N
        jMenu1.setText("Cadastro");

        menuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clientes.png"))); // NOI18N
        menuClientes.setText("Clientes");
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });
        jMenu1.add(menuClientes);

        menuFornecedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        menuFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fornecedor.png"))); // NOI18N
        menuFornecedores.setText("Fornecedores");
        menuFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFornecedoresActionPerformed(evt);
            }
        });
        jMenu1.add(menuFornecedores);

        menuFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        menuFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcionarios.png"))); // NOI18N
        menuFuncionarios.setText("Funcionários");
        menuFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuncionariosActionPerformed(evt);
            }
        });
        jMenu1.add(menuFuncionarios);
        jMenu1.add(jSeparator1);

        menuProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        menuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos.png"))); // NOI18N
        menuProdutos.setText("Produtos");
        menuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(menuProdutos);
        jMenu1.add(jSeparator2);

        menuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenu1.add(menuSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/financeiro.png"))); // NOI18N
        jMenu2.setText("Financeiro");

        menuContasReceber.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        menuContasReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/contas-receber.png"))); // NOI18N
        menuContasReceber.setText("Contas a Receber");
        menuContasReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuContasReceberActionPerformed(evt);
            }
        });
        jMenu2.add(menuContasReceber);

        menuContasPagar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        menuContasPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/contas-pagar.png"))); // NOI18N
        menuContasPagar.setText("Contas a Pagar");
        menuContasPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuContasPagarActionPerformed(evt);
            }
        });
        jMenu2.add(menuContasPagar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed
        if (clienteView == null) {
            clienteView = new ClienteView();
        }
        clienteView.setLocationRelativeTo(this);
        clienteView.setVisible(true);
    }//GEN-LAST:event_menuClientesActionPerformed

    private void menuFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFornecedoresActionPerformed
        if (fornecedorView == null) {
            fornecedorView = new FornecedorView();
        }
        fornecedorView.setLocationRelativeTo(this);
        fornecedorView.setVisible(true);
    }//GEN-LAST:event_menuFornecedoresActionPerformed

    private void menuFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuncionariosActionPerformed
        if (funcionarioView == null) {
            funcionarioView = new FuncionarioView();
        }
        funcionarioView.setLocationRelativeTo(this);
        funcionarioView.setVisible(true);
    }//GEN-LAST:event_menuFuncionariosActionPerformed

    private void menuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdutosActionPerformed
        if (produtoView == null) {
            produtoView = new ProdutoView();
        }
        produtoView.setLocationRelativeTo(this);
        produtoView.setVisible(true);
    }//GEN-LAST:event_menuProdutosActionPerformed

    private void menuContasReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuContasReceberActionPerformed
        if (contaReceberView == null) contaReceberView = new ContaReceberView();
        contaReceberView.setLocationRelativeTo(this);
        contaReceberView.setVisible(true);
    }//GEN-LAST:event_menuContasReceberActionPerformed

    private void menuContasPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuContasPagarActionPerformed
        if (contaPagarView == null) contaPagarView = new ContaPagarView();
        contaPagarView.setLocationRelativeTo(this);
        contaPagarView.setVisible(true);
    }//GEN-LAST:event_menuContasPagarActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

    private void btnAbrirCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirCaixaActionPerformed
        this.caixa = getCaixaAberto();
        if (this.caixa != null) {
            Messages.alertMessage(this, "O Caixa ja esta aberto!");
        } else {
            String valorInformado = JOptionPane.showInputDialog(this, "Informe o valor de abertura!",
                    "Informação", JOptionPane.INFORMATION_MESSAGE);

            if (valorInformado != null || !valorInformado.trim().equals("")) {
                Double valorAbertura = Double.parseDouble(valorInformado.replace(",", "."));

                caixa = new Caixa();
                caixa.setStatusCaixa(StatusCaixa.ABERTO);
                caixa.setFuncionario(funcionario);
                caixa.setDataAbertura(new Date());
                caixa.setValorAbertura(valorAbertura);
                caixa = new CaixaController().abrirCaixa(caixa);
                if (caixa == null) {
                    Messages.errorMessage(this, "Não foi possível realizar esta operação!");
                } else {
                    Messages.infoMessage(this, "Caixa aberto e pronto para vendas!");
                }
            }
        }
    }//GEN-LAST:event_btnAbrirCaixaActionPerformed

    private void btnFecharCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharCaixaActionPerformed
        this.caixa = getCaixaAberto();
        if (this.caixa == null) {
            Messages.alertMessage(this, "O caixa ja esta fechado");
        } else {
            String valorInformado = JOptionPane.showInputDialog(this, "Informe o valor de fechamento!",
                    "Informação", JOptionPane.INFORMATION_MESSAGE);

            if (valorInformado != null || !valorInformado.trim().equals("")) {
                Double valorFechamento = Double.parseDouble(valorInformado.replace(",", "."));

                caixa.setStatusCaixa(StatusCaixa.FECHADO);
                caixa.setDataFechamento(new Date());
                caixa.setValorAbertura(valorFechamento);
                if (new CaixaController().fecharCaixa(caixa)) {
                    Messages.infoMessage(this, "Caixa fechado com sucesso!");
                } else {
                    Messages.errorMessage(this, "Não foi possível realizar esta operação!");
                }
            }
        }
    }//GEN-LAST:event_btnFecharCaixaActionPerformed

    private void btnRealizarSangriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarSangriaActionPerformed
        this.caixa = getCaixaAberto();
        if (this.caixa == null) {
            Messages.alertMessage(this, "O caixa esta fechado!");
        } else {

            String valorInformado = JOptionPane.showInputDialog(this, "Informe o valor da retirada",
                    "Informação", JOptionPane.INFORMATION_MESSAGE);

            if (valorInformado != null || !valorInformado.trim().equals("")) {

                Double valorSangria = Double.parseDouble(valorInformado.replace(",", "."));

                Double valorEmCaixa = caixa.getTotalVendas() + caixa.getContasRecebidas() - caixa.getContasPagas();

                if (valorEmCaixa <= valorSangria) {
                    Messages.alertMessage(this, "Não há dinheiro suficiente em caixa!");
                } else {
                    caixa.setSangria(caixa.getSangria() + valorSangria);
                    if (new CaixaController().realizarSangria(caixa)) {
                        Messages.infoMessage(this, "Sangria realizada com sucesso!");
                    } else {
                        Messages.errorMessage(this, "Não foi possível realizar esta operação!");
                    }
                }
            }
        }
    }//GEN-LAST:event_btnRealizarSangriaActionPerformed

    private void btnNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaVendaActionPerformed
        if (novaVendaView == null) {
            novaVendaView = new NovaVendaView();
        }
        novaVendaView.setLocationRelativeTo(this);
        novaVendaView.setVisible(true);
    }//GEN-LAST:event_btnNovaVendaActionPerformed

    private Caixa getCaixaAberto() {
        return new CaixaController().getCaixaAberto();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirCaixa;
    private javax.swing.JButton btnFecharCaixa;
    private javax.swing.JButton btnNovaVenda;
    private javax.swing.JButton btnRealizarSangria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel lblStatusCaixa;
    private javax.swing.JMenuItem menuClientes;
    private javax.swing.JMenuItem menuContasPagar;
    private javax.swing.JMenuItem menuContasReceber;
    private javax.swing.JMenuItem menuFornecedores;
    private javax.swing.JMenuItem menuFuncionarios;
    private javax.swing.JMenuItem menuProdutos;
    private javax.swing.JMenuItem menuSair;
    // End of variables declaration//GEN-END:variables
}
